# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: J3ZZ
email: hello@j3zz.com
booking_email: booking@j3zz.com
description: >- # this means to ignore newlines until "baseurl:"
  French sound artist creating experimental electronic music, immersive installations,
  and audiovisual performances merging art, science, and technology.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.j3zz.com" # the base hostname & protocol for your site, e.g. http://example.com
repository: iamj3zz/website
logo: /assets/img/J3ZZ-logo-black-300px.png

# SEO Configuration
author:
  name: J3ZZ
  email: hello@j3zz.com
  twitter: j3zz

social:
  name: J3ZZ
  links:
    - https://bandcamp.com/iamj3zz
    - https://soundcloud.com/j3zz
    - https://youtube.com/@iamj3zz
    - https://vimeo.com/j3zz
    - https://facebook.com/iamj3zz
    - https://instagram.com/iamj3zz
    - https://twitter.com/j3zz
    - https://linkedin.com/in/j3zz
    - https://github.com/j3zz

tagline: "Experimental sound art merging music, generative systems, and immersive installations"
default_image: /assets/img/J3ZZ-logo-black-300px.png
lang: en_US

# Google Analytics 4
# google_analytics: G-09KW8XZSZW  # Replace with your actual GA4 measurement ID
google_analytics: G-XXXXXXXXXX  # Replace with your actual GA4 measurement ID

# Social Media
bandcamp_username: iamj3zz
soundcloud_username: j3zz
youtube_username: iamj3zz
vimeo_username: j3zz
facebook_username: iamj3zz
instagram_username: iamj3zz
twitter_username: j3zz
linkedin_username: j3zz
github_username: j3zz
twitch_username: j3zz
malt_username: j3zz

# Mailchimp Newsletter
# Form action URL from Mailchimp embedded form
mailchimp_action_url: "https://j3zz.us6.list-manage.com/subscribe/post?u=349b73ae355385780ee4a24db&id=fa86ed72ea&v_id=4617&f_id=003f22e2f0"
# Bot protection field name (honeypot)
mailchimp_bot_field: "b_349b73ae355385780ee4a24db_fa86ed72ea"
# GDPR consent field ID
mailchimp_gdpr_field: "14182"

# Events
event_description_truncate: 300  # Character limit for event descriptions before showing expand toggle (0 = never truncate)

# Collections
collections:
  portfolio:
    output: true
    permalink: /works/:name/
    sort_by: order
  events:
    output: false
    sort_by: date

# Build settings
future: true  # Allow posts/collections with future dates
plugins:
  - jekyll-feed
  - jekyll-last-modified-at
  - jekyll-seo-tag
  - jekyll-sitemap

# Include _pages directory
include:
  - _pages

# Sass settings
sass:
  sass_dir: _sass
  style: compressed
  quiet_deps: true
  verbose: false

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

exclude:
  - docs/
  - node_modules/
  - vendor/
  - CLAUDE.md
  - README.md
  - lefthook.yml
  - .claude/
